### ISSUE TITLE
Multiple overseerr user support?

### ISSUE THREAD

**Issue by misteriks** [Woahai321/list-sync#25]
Looks like a nice addition to my toolset. 
One thing I could not find if list-sync supports multiple overseer users where each user can have e.g. their own IMDB lists and when a movie is added the request gets added in overseerr to their own profile

**Comment by Woahai321** [comment]
Hey @misteriks , yes, ListSync supports multiple Overseerr users! 
There are two key aspects to this:

1. **User Selection**: ListSync allows you to specify which Overseerr user ID should be used for making requests. When multiple users are detected in your Overseerr instance, you can select which user should make the requests:

![User Selection Screenshot](https://github.com/user-attachments/assets/293ed335-cb31-4b82-8371-9ab1effccb52)

2. **Multi-Instance Setup**: For cases where you want different users to have their own watchlist syncs, you can run multiple instances of ListSync, each configured for a specific user.

## Example Multi-User Setup

Here's a Docker Compose configuration that demonstrates how to set up ListSync for multiple users:

```yaml
version: "3.8"

services:
  listsync-user1:
    image: ghcr.io/woahai321/list-sync:main
    container_name: listsync-user1
    environment:
      - OVERSEERR_URL=https://example.com
      - OVERSEERR_API_KEY=abcd1234
      - OVERSEERR_USER_ID=1
      - SYNC_INTERVAL=24
      - AUTOMATED_MODE=true
      - IMDB_LISTS=ls12345678
      - TRAKT_LISTS=1234567
      - LETTERBOXD_LISTS=https://example.com
    volumes:
      - ./data/user1:/usr/src/app/data
    restart: unless-stopped

  listsync-user2:
    image: ghcr.io/woahai321/list-sync:main
    container_name: listsync-user2
    environment:
      - OVERSEERR_URL=https://example.com
      - OVERSEERR_API_KEY=abcd1234
      - OVERSEERR_USER_ID=2
      - SYNC_INTERVAL=24
      - AUTOMATED_MODE=true
      - IMDB_LISTS=ls23456789
      - TRAKT_LISTS=1234567
      - LETTERBOXD_LISTS=https://example.com
    volumes:
      - ./data/user2:/usr/src/app/data
    restart: unless-stopped
  
  listsync-user3:
    image: ghcr.io/woahai321/list-sync:main
    container_name: listsync-user3
    environment:
      - OVERSEERR_URL=https://example.com
      - OVERSEERR_API_KEY=abcd1234
      - OVERSEERR_USER_ID=3
      - SYNC_INTERVAL=24
      - AUTOMATED_MODE=true
      - IMDB_LISTS=ls34567890
      - TRAKT_LISTS=1234567
      - LETTERBOXD_LISTS=https://example.com
    volumes:
      - ./data/user3:/usr/src/app/data
    restart: unless-stopped
```

Hope this helps, let us know if you have any other questions
